### PR TITLE
Refactor: Consolidate conditional helpers

### LINKED ISSUE #3: Small, logical helpers like if / ifAnd / ifOr should be consolidated somehow
Per the discussion in #1, we should figure out a way to simplify these.

### PR DESCRIPTION
**Pull request by erikjung**
Closes #3

#### Summary
- The `ifAnd` and `ifOr` helpers have been replaced with leaner, renamed `and` and `or` helpers.
- The `ifElse` helper has been removed.
- A new `compare` helper has been added.

This new `compare` helper is modeled after the (identically named) helper found at https://github.com/assemble/handlebars-helpers/blob/master/lib/helpers/helpers-comparisons.js, and differs by using functions from the [Ramda.js](http://ramdajs.com) library. Why? In addition to reducing a bit of code on our end, I think there are (and will be) other opportunities to leverage the functional nature of Ramda (opposed to something like Underscore) in other helper functions.

***
CC @saralohr @nicolemors

### CODE REVIEW

**Comment by tylersticka** [comment]
Heh, now that I'm reading this, I guess `&&` and `II` really _aren't_ comparisons.

Assemble just keeps those as their own little  helpers. Maybe they _are_ unique, and I conflated them with `ifEqual` because of the similarity in naming convention.

**Comment by erikjung** [comment]
@tylersticka I'd be fine with either of these scenarios:

- We add back `ifAnd` and `ifOr` (perhaps naming them differently...I feel that anything with "if" should also have an "unless" counterpart)
- We add another helper (let's call if `logic` for now) that acts like `compare` but supports the `&&` and `||` operators.

**Comment by tylersticka** [comment]
I like the first idea better but by a small margin. I'd be find with 'ifAnd' and 'ifOr' or even just 'and' and 'or'. (That's a confusing sentence.)

**Comment by erikjung** [comment]
@tylersticka Changes made, and PR description updated.

**Comment by tylersticka** [comment]
Yay! :clap:

**Pull request merged**
