### PR TITLE
Update vanilla handlebars code to what worked for me

### PR DESCRIPTION
**Pull request by Paul-Hebert**
The code in the readme did not work for me without a couple changes. This PR updates the readme with those changes:

* Fix require name
* Iterate over helpers as an object, not an array

### CODE REVIEW

**Comment by spaceninja** [comment]
The code _looks_ right, and I trust that Paul tested and it's working as intended, but I'll defer to those with more knowledge of the repo.

@tylersticka unfortunately, looking at the commit history, I think that's you.

**Comment by gerardo-rodriguez** [comment]
Out of curiosity, would things have been different if this would've been installed?

https://www.npmjs.com/package/@cloudfour/hbs-helpers

It's been a while (over 1.5 years) since I've installed/used our helpers due to the projects I've been on. I suppose this also makes me wonder if the documentation install step needs to be updated as well to install from NPM? 🤔

**Comment by Paul-Hebert** [comment]
@gerardo-rodriguez , that's a good question. I'm not sure. I followed the installation steps from the README and ran this command: `npm install --save-dev cloudfour/core-hbs-helpers.git`

That resulted in this being added to my `package.json`:
`    "@cloudfour/hbs-helpers": "github:cloudfour/core-hbs-helpers",`

Should I have installed that alternate package?

**Comment by gerardo-rodriguez** [comment]
> @gerardo-rodriguez , that's a good question. I'm not sure. I followed the installation steps from the README and ran this command: `npm install --save-dev cloudfour/core-hbs-helpers.git`
> 
> That resulted in this being added to my `package.json`:
> ` "@cloudfour/hbs-helpers": "github:cloudfour/core-hbs-helpers",`
> 
> Should I have installed that alternate package?

Good question, @Paul-Hebert. Technically, either is fine. There was an effort some time ago to get our shared packages published on NPM. I would imagine it seems we should default to installing from NPM. 

Do you agree @cloudfour/dev?

**Comment by Paul-Hebert** [comment]
That makes sense to me. If that's the case I wonder if it's the install step that needs to be updated instead of the code examples.

**Comment by gerardo-rodriguez** [comment]
> That makes sense to me. If that's the case I wonder if it's the install step that needs to be updated instead of the code examples.

@Paul-Hebert That is the same question I have. :) 

Would you be able to test it out? 😬

**Comment by gerardo-rodriguez** [comment]
Also, FWIW, the last time I was on a project that used these HBS helpers (again, a long time ago in web years) it was using Gulp so the Vanilla example may have been incorrect and we never caught that. 🙈

**Comment by Paul-Hebert** [comment]
@gerardo-rodriguez yeah, sure. I can test the npm package, and see what's what with the vanilla instructions.

**Comment by Paul-Hebert** [comment]
@gerardo-rodriguez , I ran into the same problems when using the npm package.

- The package name in README was incorrect
- The vanilla JS example treated `helpers` as an array instead of an object.

**Comment by gerardo-rodriguez** [comment]
> @gerardo-rodriguez , I ran into the same problems when using the npm package.
> 
> * The package name in README was incorrect
> * The vanilla JS example treated `helpers` as an array instead of an object.

That makes sense, thanks for testing @Paul-Hebert! 👍

**Comment by Paul-Hebert** [comment]
Sure thing!

**Pull request merged**
